# Generated by Django 3.1.2 on 2021-04-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyname', models.CharField(db_column='propertyName', max_length=100)),
                ('propertyarea', models.FloatField(blank=True, db_column='propertyArea', null=True)),
                ('propertyrent', models.IntegerField(db_column='propertyRent')),
                ('propertydeposit', models.IntegerField(db_column='propertyDeposit')),
                ('propertymaintenancetype', models.CharField(db_column='propertyMaintenanceType', max_length=20)),
                ('propertytype', models.CharField(db_column='propertyType', max_length=20)),
                ('propertyfloor', models.IntegerField(db_column='propertyFloor')),
                ('propertyage', models.CharField(db_column='propertyAge', max_length=15)),
                ('mobileno', models.CharField(db_column='mobileNo', max_length=15)),
                ('tenanttype', models.CharField(db_column='tenantType', max_length=10)),
                ('furnishingtype', models.CharField(db_column='furnishingType', max_length=15)),
                ('availablefrom', models.DateField(db_column='availableFrom')),
                ('parkingtype', models.CharField(db_column='parkingType', max_length=20)),
                ('propertydescription', models.CharField(db_column='propertyDescription', max_length=100)),
                ('totalbeds', models.IntegerField(db_column='totalBeds')),
                ('totalbathrooms', models.IntegerField(db_column='totalBathrooms')),
                ('totalbalcony', models.IntegerField(db_column='totalBalcony')),
                ('watersupplytype', models.CharField(db_column='waterSupplyType', max_length=20)),
                ('gymstatus', models.CharField(db_column='gymStatus', max_length=10)),
                ('gatedsecuritystatus', models.CharField(db_column='gatedSecurityStatus', max_length=10)),
                ('propertystate', models.CharField(db_column='propertyState', max_length=30)),
                ('propertycity', models.CharField(db_column='propertyCity', max_length=30)),
                ('amenities', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('lastmodified', models.DateTimeField(db_column='lastModified')),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=700, null=True)),
                ('usertype', models.IntegerField(db_column='userType')),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
